version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format_overrides:
      - goos: darwin
        format: zip
      - goos: linux
        format: tar.gz
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  - name: imgcat
    publish: true
    summary: Display images and gifs in your terminal
    description: Display images and gifs in your terminal
    apps:
      imgcat:
        command: imgcat
        plugs:
          - home
          - removable-media

brews:
  - name: imgcat
    skip_upload: false
    repository:
      owner: danielgatis
      name: homebrew-imgcat
    url_template: "https://github.com/danielgatis/imgcat/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    description: Display images and gifs in your terminal

scoops:
  - description: Display images and gifs in your terminal
    url_template: "https://github.com/danielgatis/imgcat/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: danielgatis
      name: scoop-imgcat
