# This file was generated by GoReleaser. DO NOT EDIT.
class Imgcat < Formula
  desc "Display images and gifs in your terminal"
  homepage ""
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/danielgatis/imgcat/releases/download/v1.0.2/imgcat_1.0.2_Darwin_x86_64.tar.gz"
    sha256 "5cfbe0167722a7098e2b122dcce6bd30f0efef285be82b17629ecdd932e6a3ab"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/danielgatis/imgcat/releases/download/v1.0.2/imgcat_1.0.2_Linux_x86_64.tar.gz"
    sha256 "645b457f93144b0a9556faef5f9af024f89a6c98f046343bc65ba567f2a98f27"
  end

  depends_on "go"

  def install
    bin.install "imgcat"
  end
end
